### ISSUE TITLE
NFT controller v2

### ISSUE THREAD

**Issue by sshubhamagg** [getsafle/nft-controller#10]
Updates to be implemented:
Method to detect NFT in a wallet and get NFT details

Description:
Accept chain and public address and return all NFT's in the wallet on the specified chain.

Parameters:
chain, publicAddress

Response:
Array of NFT's in the wallet on the selected chain

API to be used
[https://nft.metafi.codefi.network/accounts/{address}/nfts

**Comment by ARJUN-R34** [comment]
Enable the NFT detection on Ethereum, BSC and Polygon chain.
